(in-package :pq)

(defun define-si-units ()
  (define-unit-prefixes
    (yocto y -24)
    (zepto z -21)
    (atto a  -18)
    (femto f -15)
    (pico p -12)
    (nano n -9)
    (micro u -6)
    (milli m -3)
    (centi c -2)
    (deci d -1)
    (deca da 1)
    (hecto h 2)
    (kilo k 3)
    (mega meg 6)
    (giga g 9)
    (tera t 12)
    (peta pet 15)
    (exa e 18)
    (zetta zet 21)
    (yotta yot 24)
    (kibi ki 1 :base 1024)
    (mebi mi 2 :base 1024)
    (gibi gi 3 :base 1024)
    (tebi ti 4 :base 1024)
    (pebi pi 5 :base 1024)
    (exbi ei 6 :base 1024)
    (zebi zi 7 :base 1024)
    (yobi yi 8 :base 1024))
  (define-units
    ;; SI base units
    (metre :abbrev m :alias meter :prefix-max 3)
    (gram :abbrev g :prefix-max 3)
    (second :abbrev s :prefix-max 0)
    (ampere :abbrev a)
    (kelvin :abbrev k :prefix-max 0)
    (mol)
    (candela :abbrev cd)
    ;; Named units derived from SI base units
    (radian :def (1) :abbrev rad)
    (steradian :def (1) :abbrev sr)
    (hertz :def (1 / second) :abbrev hz)
    (newton :def (1 kilogram metre / second ^ 2) :abbrev n)
    (pascal :def (1 newton / metre ^ 2) :abbrev pa)
    (joule :def (1 newton metre) :abbrev j)
    (watt :def (1 joule / second) :abbrev w)
    (coulomb :def (1 ampere second) :abbrev c)
    (volt :def (1 watt / ampere) :abbrev v)
    (farad :def (1 coulomb / volt) :abbrev f)
    (ohm :def (1 volt / ampere))
    (siemens :def (1 ampere / volt))
    (weber :def (1 volt second) :abbrev wb)
    (tesla :def (1 weber / metre ^ 2) :abbrev t)
    (henry :def (1 weber / ampere))
    (celsius :def (1 kelvin) :prefix-max 0 :prefix-min 0)
    (lumen :def (1 candela steradian) :abbrev lm)
    (lux :def (1 lumen / metre ^ 2) :abbrev lx)
    (becquerel :def (1 / second) :abbrev bq)
    (gray :def (1 joule / kilogram) :abbrev gy)
    (sievert :def (1 joule / kilogram) :abbrev sv)
    (katal :def (1 mol / second) :abbrev kat)
    (byte :def (1) :abbrev b :prefix-min 0 :base (10 1024))
    ;; Non-SI units accepted for use with SI
    (minute :def (60 second) :abbrev min)
    (hour :def (60 minute) :abbrev h)
    (day :def (24 hour) :abbrev d)
    (litre :def (1 decimetre ^ 3) :abbrev l)
    (tonne :def (1000 kilogram) :prefix-min 0)
    (astronomical-unit :def (149597870700 metre) :abbrev au)
    (electronvolt :def (1.6021765314d-19 joule) :abbrev ev)
    (atomic-mass :def (1.6605388628e-27 kilogram) :abbrev u)))
(export 'define-si-units)
