(in-package :pq)

(defun define-si-units ()
  (define-unit-prefixes
    (yocto y -24)
    (zepto z -21)
    (atto a  -18)
    (femto f -15)
    (pico p -12)
    (nano n -9)
    (micro u -6)
    (milli m -3)
    (centi c -2)
    (deci d -1)
    (deca da 1)
    (hecto h 2)
    (kilo k 3)
    (mega meg 6)
    (giga g 9)
    (tera t 12)
    (peta pet 15)
    (exa e 18)
    (zetta zet 21)
    (yotta yot 24)
    ;(kibi ki 1 :base 1024)
    ;(mebi mi 2 :base 1024)
    ;(gibi gi 3 :base 1024)
    ;(tebi ti 4 :base 1024)
    ;(pebi pi 5 :base 1024)
    ;(exbi ei 6 :base 1024)
    ;(zebi zi 7 :base 1024)
    ;(yobi yi 8 :base 1024)
    )
  ;; SI base units
  (define-unit metre :abbrev m :alias meter)
  (define-unit gram :abbrev g)
  (define-unit second :abbrev s)
  (define-unit ampere :abbrev a)
  (define-unit kelvin :abbrev k)
  (define-unit mol)
  (define-unit candela :abbrev cd)
  ;; Named units derived from SI base units
  (define-unit radian :def (1) :abbrev rad)
  (define-unit steradian :def (1) :abbrev sr)
  (define-unit hertz :def (1 / second) :abbrev hz)
  (define-unit newton :def (1 kilogram metre / second ^ 2) :abbrev n)
  ;(define-unit pascal :def (1 newton / metre ^ 2) :abbrev pa)
  (define-unit joule :def (1 newton metre) :abbrev j)
  (define-unit watt :def (1 joule / second) :abbrev w)
  (define-unit coulomb :def (1 ampere second) :abbrev c)
  (define-unit volt :def (1 watt / ampere) :abbrev v)
  (define-unit farad :def (1 coulomb / volt) :abbrev f)
  (define-unit ohm :def (1 volt / ampere))
  (define-unit siemens :def (1 ampere / volt))
  (define-unit weber :def (1 volt second) :abbrev wb)
  (define-unit tesla :def (1 weber / metre ^ 2) :abbrev t)
  (define-unit henry :def (1 weber / ampere))
  (define-unit celsius :def (1 kelvin))
  (define-unit lumen :def (1 candela steradian) :abbrev lm)
  (define-unit lux :def (1 lumen / metre ^ 2) :abbrev lx)
  (define-unit becquerel :def (1 / second) :abbrev bq)
  (define-unit gray :def (1 joule / kilogram) :abbrev gy)
  (define-unit sievert :def (1 joule / kilogram) :abbrev sv)
  (define-unit katal :def (1 mol / second) :abbrev kat)
  (define-unit byte :def (1) :abbrev b)
  ;; Non-SI units accepted for use with SI
  (define-unit minute :def (60 second) :abbrev min)
  (define-unit hour :def (60 minute) :abbrev h)
  ;(define-unit day :def (24 hour) :abbrev d)
  (define-unit litre :def (1 decimetre ^ 3) :abbrev l)
  (define-unit tonne :def (1000 kilogram))
  (define-unit astronomical-unit :def (149597870700 metre) :abbrev au)
  ;(define-unit electronvolt :def (1.6021765314d-19 joule) :abbrev ev)
  ;(define-unit atomic-mass :def (1.6605388628e-27 kilogram) :abbrev u)
)
(export 'define-si-units)
